import type { Recipe } from "@/types/recipe";

export const sampleRecipes: Recipe[] = [
  {
    id: "1",
    title: "Classic Spaghetti Carbonara",
    slug: "classic-spaghetti-carbonara",
    ingredients: [
      "400g spaghetti",
      "200g pancetta or guanciale, diced",
      "4 large eggs",
      "100g Pecorino Romano cheese, grated",
      "50g Parmesan cheese, grated",
      "2 cloves garlic, minced",
      "Salt and black pepper to taste",
      "Fresh parsley for garnish",
    ],
    instructions: [
      "Bring a large pot of salted water to a boil and cook the spaghetti according to package instructions until al dente.",
      "While the pasta is cooking, heat a large skillet over medium heat. Add the pancetta and cook until crispy, about 5-7 minutes.",
      "In a bowl, whisk together the eggs, grated cheeses, and a generous amount of black pepper.",
      "When the pasta is done, reserve 1 cup of pasta water, then drain the pasta.",
      "Working quickly, add the hot pasta to the skillet with the pancetta. Remove from heat.",
      "Pour the egg and cheese mixture over the pasta, stirring constantly to create a creamy sauce. Add a splash of reserved pasta water if needed to loosen the sauce.",
      "Serve immediately, garnished with additional grated cheese and parsley.",
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    image: "/receptik/placeholder.svg?height=300&width=400",
    tags: ["Italian", "Pasta", "Dinner"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Avocado Toast with Poached Egg",
    slug: "avocado-toast-with-poached-egg",
    ingredients: [
      "2 slices of sourdough bread",
      "1 ripe avocado",
      "2 eggs",
      "1 tablespoon white vinegar",
      "Salt and pepper to taste",
      "Red pepper flakes (optional)",
      "Fresh cilantro or microgreens for garnish",
      "Lemon juice",
    ],
    instructions: [
      "Toast the bread slices until golden and crisp.",
      "Cut the avocado in half, remove the pit, and scoop the flesh into a bowl. Mash with a fork and season with salt, pepper, and a squeeze of lemon juice.",
      "For the poached eggs, bring a pot of water to a gentle simmer and add the vinegar.",
      "Crack each egg into a small cup. Create a gentle whirlpool in the water and carefully slide the eggs in.",
      "Cook for 3-4 minutes for a runny yolk, then remove with a slotted spoon.",
      "Spread the mashed avocado on the toast slices, top each with a poached egg.",
      "Season with salt, pepper, and red pepper flakes if desired. Garnish with fresh herbs.",
    ],
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    image: "/receptik/placeholder.svg?height=300&width=400",
    tags: ["Breakfast", "Vegetarian", "Healthy"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Thai Green Curry",
    slug: "thai-green-curry",
    ingredients: [
      "400ml coconut milk",
      "3-4 tbsp green curry paste",
      "500g chicken breast, sliced",
      "1 red bell pepper, sliced",
      "1 zucchini, sliced",
      "Handful of green beans",
      "2 tbsp fish sauce",
      "1 tbsp palm sugar or brown sugar",
      "Fresh Thai basil leaves",
      "2 kaffir lime leaves",
      "1 tbsp vegetable oil",
      "Jasmine rice for serving",
    ],
    instructions: [
      "Heat oil in a large pan or wok over medium heat. Add the curry paste and cook for 1-2 minutes until fragrant.",
      "Add half the coconut milk and bring to a simmer, stirring to combine with the curry paste.",
      "Add the chicken and cook for 5 minutes until nearly cooked through.",
      "Add the vegetables, remaining coconut milk, fish sauce, and sugar. Stir well.",
      "Simmer for 10 minutes until the vegetables are tender and the chicken is fully cooked.",
      "Stir in the Thai basil leaves and lime leaves.",
      "Serve hot with jasmine rice.",
    ],
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    image: "/receptik/placeholder.svg?height=300&width=400",
    tags: ["Thai", "Curry", "Dinner", "Spicy"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
