interface Resources {
  translation: {
    common: {
      add: "Add";
      addRecipe: "Add Recipe";
      addToFavorites: "Add to favorites";
      allRightsReserved: "All rights reserved";
      appName: "Receptik";
      back: "Back";
      backToRecipes: "Back to Recipes";
      cancel: "Cancel";
      clear: "Clear";
      close: "Close";
      confirm: "Confirm";
      cookingMode: "Cooking Mode";
      default: "Default";
      delete: "Delete";
      edit: "Edit";
      filters: "Filters";
      finish: "Finish";
      gridView: "Grid View";
      lastUpdated: "Updated";
      listView: "List View";
      loading: "Loading...";
      moreActions: "More Actions";
      nextStep: "Next Step";
      noDescription: "No description available";
      noRecipesFound: "No recipes found";
      noRecipesFoundDesc: "No recipes match {{searchQuery}}. Try adjusting your search or filters.";
      noResultsFound: "No results found";
      notFound: "Not found";
      pageNotFound: "Page not found";
      pageNotFoundDesc: "The page you&apos;re looking for doesn&apos;t exist or has been removed.";
      prevStep: "Previous Step";
      reload: "Reload";
      reset: "Reset";
      save: "Save";
      search: "Search";
      share: "Share";
      showLess: "Show less";
      showMore: "Show more";
      startCooking: "Cook";
      toHomePage: "Go to homepage";
      today: "Today is";
    };
    desktop: {
      selectRecipe: "Select Recipe";
      viewDetailsPrompt: "View details for {{recipeTitle}}";
      viewSample: "View Sample";
    };
    errorBoundary: {
      componentStack: "Component Stack";
      errorInComponent: "Error in {{componentName}}";
      message: "Message";
      refresh: "Refresh Page";
      resetData: "Reset All Data";
      resetDataConfirm: "Are you sure you want to reset all data? This action cannot be undone and will delete all your recipes and settings.";
      showErrorDetails: "Show Error Details";
      stackTrace: "Stack Trace";
      time: "Time";
    };
    forms: {
      addIngredient: "Add Ingredient";
      addStep: "Add Step";
      author: "Author";
      authorPlaceholder: "Enter author name";
      cancelIngredient: "Cancel Ingredient";
      category: "Category";
      categoryPlaceholder: "Add a category (e.g. Vegetarian, Dessert)";
      cookTime: "Cook Time";
      createRecipe: "Create New Recipe";
      createRecipeDescription: "Create a new recipe";
      cuisine: "Cuisine";
      cuisinePlaceholder: "Add a cuisine (e.g. American, Italian)";
      deleteIngredient: "Delete Ingredient";
      description: "Description";
      descriptionPlaceholder: "A brief description of your recipe...";
      durationPresets: {
        long: "Long (1h)";
        medium: "Medium (30m)";
        quick: "Quick (5m)";
        short: "Short (15m)";
        veryLong: "Very Long (2h)";
      };
      editRecipe: "Edit Recipe";
      editRecipeDescription: "Edit an existing recipe";
      failedToSubmit: "Failed to submit the form. Please try again.";
      imagePreview: "Preview of {{name}}";
      imageRemoved: "Image removed";
      imageUploadButton: "Choose images to upload";
      imageUploadButtonDescription: "Click to select images from your device";
      imageUploadDescription: "Upload images for your recipe. Supported formats: JPEG, PNG, WebP. Maximum size: 5MB.";
      imageUploadError: "Failed to upload image";
      imageUploadSuccess: "Image uploaded successfully";
      images: "Images";
      imagesCount: "{{current}}/{{max}} images";
      ingredientAmount: "Amount";
      ingredientName: "Ingredient Name";
      ingredientNamePlaceholder: "Ingredient name";
      ingredientPlaceholder: "Ingredient {{index}}";
      ingredientUnit: "Unit";
      ingredients: "Ingredients";
      instructions: "Instructions";
      keywords: "Keywords";
      keywordsPlaceholder: "Add a keyword (e.g. grandma, affordable)";
      namePlaceholder: "Enter recipe name";
      noDuration: "No duration set";
      prepTime: "Prep Time";
      presetDuration: "Cooking Duration";
      presetDurationPlaceholder: "Choose a preset duration";
      recipeName: "Recipe Name";
      removeImage: "Remove image {{name}}";
      saveIngredient: "Save Ingredient";
      saveRecipe: "Save Recipe";
      selectUnit: "Select Unit";
      servings: "Servings";
      servingsPlaceholder: "e.g. 4";
      stepPlaceholder: "Step {{index}}";
      totalTime: "Total Time";
      uploadImages: "Upload Images";
      uploadedImages: "Uploaded Images";
      uploading: "Uploading...";
    };
    home: {
      addYourFirst: "Add your first recipe to get started";
      allRecipes: "All";
      createFirstRecipe: "Create First Recipe";
      errorLoadingRecipes: "Error loading recipes";
      loadingRecipes: "Loading Recipes...";
      noRecipes: "No recipes yet";
      searchPlaceholder: "Search by name or keyword...";
      subtitle: "Browse and manage your favorite recipes";
      title: "My Recipes";
    };
    importRecipes: {
      confirmImport: "Confirm Import ({{count}})";
      errorParsingJson: "Error parsing JSON file. Please check its format.";
      errorReadingFile: "Error reading file.";
      importFailed: "Import failed. See console for details.";
      invalidJsonFormat: "The JSON file does not contain a valid recipe or array of recipes.";
      moreIngredients: "and {{count}} more";
      moreInstructions: "and {{count}} more";
      noFileSelected: "Please select a JSON file.";
      noRecipesToImport: "No recipes to import. Please select a file first.";
      noValidRecipesFound: "No valid recipes found in the selected file.";
      noValidRecipesInArray: "The selected file contains an array, but no valid recipes were found within it.";
      notJsonFile: "Please select a valid JSON file.";
      preview: "Preview";
      previewDescription: "Please review the recipes below before importing.";
      previewFailed: "Failed to generate preview. See console for details.";
      previewList: "Recipe preview list";
      previewTitle: "Preview Recipes";
      processing: "Processing...";
      selectFile: "Select File";
      someInvalidRecipes: "Some items in the file were not valid recipes and were skipped.";
      success: "Successfully imported {{count}} recipes!";
    };
    installPrompt: {
      howToInstall: "How to Install";
      installApp: "Install App";
      installAppDescription: "While direct installation isn't supported on your browser, you can still add this app to your home screen for quick access.";
      instructions: {
        chrome: '**Chrome/Edge on Android:** Tap the three dots menu in the top-right and select "Add to Home screen".';
        other: '**Other Browsers/Platforms:** Look for an "Add to Home screen", "Install app", or similar option in your browser\'s menu.';
        safari: '**Safari on iOS:** Tap the Share button (square with an arrow pointing up) and select "Add to Home Screen".';
        title: "Instructions:";
      };
      stepsMayVary: " These steps may vary slightly depending on your browser and device.";
    };
    language: {
      label: "Language";
      supported: {
        en: "English";
        ru: "Russian";
      };
    };
    modals: {
      deleteRecipe: "Delete Recipe";
      deleteRecipeConfirm: "Are you sure you want to delete {{recipeTitle}}? This action cannot be undone.";
      shareRecipe: "Share Recipe";
      shareRecipeDesc: "Share {{recipeTitle}} with friends and family";
    };
    navigation: {
      importExport: "Import/Export";
      mealPlan: "Meal Plan";
      myRecipes: "My Recipes";
      settings: "Settings";
    };
    recipe: {
      cookTime: "Cooking Time";
      cookingMode: "Cooking Mode";
      finish: "Finish";
      ingredient_interval: "(1)[ingredient];(2-inf)[ingredients];";
      ingredients: "Ingredients";
      instructions: "Instructions";
      keywords: "Keywords";
      nextStep: "Next Step";
      noImages: "No images";
      noKeywords: "No keywords";
      prepTime: "Preparation Time";
      prevStep: "Previous Step";
      recipeNotFound: "Recipe not found";
      recipeNotFoundDesc: "The recipe you're looking for doesn't exist or has been removed.";
      searchResults: "Results found: {{count}}";
      servings: "Servings";
      servings_interval: "(1)[serving];(2-inf)[servings];";
      startCooking: "Cook";
      step: "Step";
      step_interval: "(1)[step];(2-inf)[steps];";
      title: "Recipe Details";
      totalTime: "Total Time";
    };
    reloadPrompt: {
      newUpdateAvailable: "New update available";
      offlineDescription: "You can now use the app even without an internet connection.";
      readyForOfflineUse: "App ready for offline use";
      updateDescription: 'Click "Reload" to get the latest version of the app.';
    };
    settings: {
      appearance: "Appearance";
      dataManagement: "Data Management";
      debug: "Debug";
      exportAllRecipesDesc: "Export all your recipes as a JSON file for backup or sharing.";
      exportError: "Error exporting recipes";
      exportSuccess: "All recipes exported as JSON";
      importRecipes: "Import Recipes";
      importRecipesDesc: "Import recipes from a JSON file exported from Receptik or another compatible app.";
      importing: "Importing...";
      resetAllData: "Reset All Data";
      resetAllDataDesc: "Delete all your recipes and reset the app to its default state. This action cannot be undone.";
      resetConfirmationDescription: "Are you sure you want to reset all data? This action cannot be undone.";
      resetConfirmationTitle: "Reset All Data";
      resetError: "Error deleting all data";
      resetSuccess: "All data has been deleted";
      stayTuned: "Coming soon! Stay tuned for updates.";
      title: "Settings";
    };
    share: {
      copiedToClipboard: "Recipe copied to clipboard!";
      copyDescription: "Copies the full recipe text so you can paste it anywhere.";
      copyToClipboard: "Copy to Clipboard";
      email: "Email";
      error: "Could not share recipe";
      export: "Export";
      exportAllAsJson: "Export All";
      exportAllRecipes: "Export all recipes as JSON";
      exportThisRecipe: "Export this recipe";
      facebook: "Facebook";
      image: "Image";
      link: "Link";
      nativeDescription: "Send to apps like WhatsApp, Telegram, or Mail.";
      social: "Share Recipe";
      successImage: "Recipe exported as image";
      successTxt: "Recipe exported as text file";
      text: "Text";
      twitter: "Twitter";
    };
    theme: {
      dark: "Dark";
      label: "Theme";
      light: "Light";
      system: "System";
    };
    time: {
      hourShort: "h";
      hour_interval: "(1)[hour];(2-inf)[hours];";
      hours: "Hours";
      invalid: "Invalid duration";
      lessThanMinute: "less than a minute";
      minuteShort: "m";
      minute_interval: "(1)[minute];(2-inf)[minutes];";
      minutes: "Minutes";
      secondShort: "s";
      seconds: "Seconds";
    };
    timer: {
      clearTimer: "Clear Timer";
      notification: {
        endBody: "Your timer has finished.";
        endTitle: "Timer Complete!";
        startBody: "Your timer is now active.";
        startTitle: "Timer Running";
      };
      pause: "Pause";
      reset: "Reset";
      resume: "Resume";
      setTimer: "Set Timer";
      setTimerDescription: "Enter the duration for your timer.";
      setTimerTitle: "Set Timer";
      start: "Start";
    };
    units: {
      length: {
        cm: "centimeter";
        cm_interval: "(1)[centimeter];(2-inf)[centimeters];";
        cm_short: "cm";
        ft: "foot (US)";
        "ft-imp": "foot (Imperial)";
        "ft-imp_interval": "(1)[foot];(2-inf)[feet];";
        "ft-imp_short": "ft (imp)";
        ft_interval: "(1)[foot];(2-inf)[feet];";
        ft_short: "ft (US)";
        in: "inch (US)";
        "in-imp": "inch (Imperial)";
        "in-imp_interval": "(1)[inch];(2-inf)[inches];";
        "in-imp_short": "in (imp)";
        in_interval: "(1)[inch];(2-inf)[inches];";
        in_short: "in (US)";
        m: "meter";
        m_interval: "(1)[meter];(2-inf)[meters];";
        m_short: "m";
        mm: "millimeter";
        mm_interval: "(1)[millimeter];(2-inf)[millimeters];";
        mm_short: "mm";
        yd: "yard (US)";
        "yd-imp": "yard (Imperial)";
        "yd-imp_interval": "(1)[yard];(2-inf)[yards];";
        "yd-imp_short": "yd (imp)";
        yd_interval: "(1)[yard];(2-inf)[yards];";
        yd_short: "yd (US)";
      };
      other: {
        clove: "clove";
        clove_interval: "(1)[clove];(2-inf)[cloves];";
        drop: "drop";
        drop_interval: "(1)[drop];(2-inf)[drops];";
        feather: "feather";
        feather_interval: "(1)[feather];(2-inf)[feathers];";
        head: "head";
        head_interval: "(1)[head];(2-inf)[heads];";
        leaf: "leaf";
        leaf_interval: "(1)[leaf];(2-inf)[leaves];";
        optional: "optional";
        piece: "piece";
        piece_interval: "(1)[piece];(2-inf)[pieces];";
        pinch: "pinch";
        pinch_interval: "(1)[pinch];(2-inf)[pinches];";
        slice: "slice";
        slice_interval: "(1)[slice];(2-inf)[slices];";
        sprig: "sprig";
        sprig_interval: "(1)[sprig];(2-inf)[sprigs];";
        toTaste: "to taste";
      };
      volume: {
        "cup-imp": "cup (Imperial)";
        "cup-imp_interval": "(1)[cup];(2-inf)[cups];";
        "cup-imp_short": "cup (imp)";
        "cup-us": "cup (US)";
        "cup-us_interval": "(1)[cup];(2-inf)[cups];";
        "cup-us_short": "cup (US)";
        "fl-oz-imp": "fluid ounce (Imperial)";
        "fl-oz-imp_interval": "(1)[fluid ounce];(2-inf)[fluid ounces];";
        "fl-oz-imp_short": "fl oz (imp)";
        "fl-oz-us": "fluid ounce (US)";
        "fl-oz-us_interval": "(1)[fluid ounce];(2-inf)[fluid ounces];";
        "fl-oz-us_short": "fl oz (US)";
        "gal-imp": "gallon (Imperial)";
        "gal-imp_interval": "(1)[gallon];(2-inf)[gallons];";
        "gal-imp_short": "gal (imp)";
        "gal-us": "gallon (US)";
        "gal-us_interval": "(1)[gallon];(2-inf)[gallons];";
        "gal-us_short": "gal (US)";
        l: "liter";
        l_interval: "(1)[liter];(2-inf)[liters];";
        l_short: "L";
        "metric-cup": "metric cup";
        "metric-cup_interval": "(1)[metric cup];(2-inf)[metric cups];";
        "metric-cup_short": "cup (metric)";
        ml: "milliliter";
        ml_interval: "(1)[milliliter];(2-inf)[milliliters];";
        ml_short: "ml";
        oz: "ounce";
        oz_interval: "(1)[ounce];(2-inf)[ounces];";
        oz_short: "oz";
        "pt-imp": "pint (Imperial)";
        "pt-imp_interval": "(1)[pint];(2-inf)[pints];";
        "pt-imp_short": "pt (imp)";
        "pt-us": "pint (US)";
        "pt-us_interval": "(1)[pint];(2-inf)[pints];";
        "pt-us_short": "pt (US)";
        "qt-imp": "quart (Imperial)";
        "qt-imp_interval": "(1)[quart];(2-inf)[quarts];";
        "qt-imp_short": "qt (imp)";
        "qt-us": "quart (US)";
        "qt-us_interval": "(1)[quart];(2-inf)[quarts];";
        "qt-us_short": "qt (US)";
        tbsp: "tablespoon";
        "tbsp-imp": "tablespoon (Imperial)";
        "tbsp-imp_interval": "(1)[tablespoon];(2-inf)[tablespoons];";
        "tbsp-imp_short": "tbsp (imp)";
        "tbsp-us": "tablespoon (US)";
        "tbsp-us_interval": "(1)[tablespoon];(2-inf)[tablespoons];";
        "tbsp-us_short": "tbsp (US)";
        tbsp_interval: "(1)[tablespoon];(2-inf)[tablespoons];";
        tbsp_short: "tbsp";
        tsp: "teaspoon";
        "tsp-imp": "teaspoon (Imperial)";
        "tsp-imp_interval": "(1)[teaspoon];(2-inf)[teaspoons];";
        "tsp-imp_short": "tsp (imp)";
        "tsp-us": "teaspoon (US)";
        "tsp-us_interval": "(1)[teaspoon];(2-inf)[teaspoons];";
        "tsp-us_short": "tsp (US)";
        tsp_interval: "(1)[teaspoon];(2-inf)[teaspoons];";
        tsp_short: "tsp";
      };
      weight: {
        g: "gram";
        g_interval: "(1)[gram];(2-inf)[grams];";
        g_short: "g";
        kg: "kilogram";
        kg_interval: "(1)[kilogram];(2-inf)[kilograms];";
        kg_short: "kg";
        lb: "pound";
        lb_interval: "(1)[pound];(2-inf)[pounds];";
        lb_short: "lb";
        oz: "ounce";
        oz_interval: "(1)[ounce];(2-inf)[ounces];";
        oz_short: "oz";
      };
    };
    validation: {
      allowedImageTypes: "Only JPEG, PNG, and WebP images are allowed";
      authorTooLong: "Author name must not exceed 50 characters.";
      authorTooShort: "Author name must be at least 1 character.";
      cookTimeEmpty: "Cooking time cannot be empty.";
      cookTimeInvalid: "Please enter a valid cooking time.";
      descriptionTooLong: "Description must not exceed 500 characters.";
      fileTooLarge: "File is too large";
      ingredientAmountRequired: "Amount is required and must be a positive number for this unit.";
      ingredientNameRequired: "Ingredient name is required.";
      ingredientRequired: "At least one ingredient is required.";
      instructionRequired: "At least one instruction step is required.";
      instructionStepRequired: "Instruction step is required.";
      invalidFileType: "Invalid file type";
      maxFileSize: "Maximum file size is {{size}}";
      maxImages: "Maximum {{count}} images allowed";
      nameTooLong: "Recipe name must not exceed 50 characters.";
      nameTooShort: "Recipe name must be at least 2 characters.";
      prepTimeInvalid: "Please enter a valid preparation time.";
      servingsTooFew: "Servings must be at least 1.";
      servingsTooMany: "Servings must be at most 100.";
      tooManyImages: "Too many images";
      tryAgain: "Please try again";
      uploadFailed: "Failed to upload image";
    };
  };
}

export default Resources;
